# Generated by Django 6.1.1 on 2026-09-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='bi-book', help_text='Clase de Bootstrap Icons, ej: bi-briefcase', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seleccion', 'Selección múltiple'), ('completar', 'Completar (fill in the gaps)'), ('vf', 'Verdadero o falso')], default='seleccion', max_length=10)),
                ('nivel', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio alto')], default='A1', max_length=2)),
                ('enunciado', models.TextField(help_text="En 'completar', usá ___ (tres guiones bajos) donde va el hueco.")),
                ('respuesta_correcta', models.CharField(blank=True, help_text="Solo para 'completar'. Si hay varias respuestas válidas, separalas con |", max_length=200)),
                ('es_verdadero', models.BooleanField(blank=True, help_text="Solo para 'verdadero o falso'.", null=True)),
                ('explicacion', models.TextField(blank=True, help_text='Opcional: se muestra después de responder.')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.ejercicio')),
            ],
            options={
                'verbose_name_plural': 'opciones',
            },
        ),
    ]
